### ISSUE TITLE
Header is gone until scrolled on the contact-us page.

### ISSUE THREAD

**Issue by haystack-hq** [haystack-hq/website#16]
Navigate to https://www.haystackhq.com/contact-us 

Notice the header is gone.
Now scroll.. Header will show once you scroll.

https://drive.google.com/file/d/1yafHX1PSMEDaXdKYgCja5l5qtDmxTIfh/view

**Comment by haystack-hq** [comment]
I notice that is actually happens on contact us and early access.

**Comment by jajajaime** [comment]
#17 did not resolve the issue

**Comment by jajajaime** [comment]
https://github.com/haystack-hq/website/commit/c474f79514f2cc5c02d82138037cdb2872b2706a fixes it.
