### ISSUE TITLE
Capitalization error "Your own Cloud Account"

### ISSUE THREAD

**Issue by haystack-hq** [haystack-hq/website#6]
I think that the "Your own Cloud Account" should be "Your Own Cloud Account". All of the other labels in this area are capital first letter in each word.

Home page > Pricing section

**Comment by goldbatzmaru** [comment]
Issue fixed in https://github.com/haystack-hq/website/tree/capitilization-fix

**Comment by jajajaime** [comment]
The cloud pricing also says 

> * Choose a cloud provider

which should probably change as well

**Comment by jajajaime** [comment]
Should the text in my previous comment be changed as well?
