### ISSUE TITLE
Many of the assets are very large. Can they be reduced?

### ISSUE THREAD

**Issue by haystack-hq** [haystack-hq/website#7]
If you look at the asset: static/img/demos/demo-slider@2x.jpg  it is 474KB, seem too large and should be reduced for a fast page load.

**Comment by goldbatzmaru** [comment]
Many images were left over from the theme and did not need to be included in the repo.

Two images were downsized 100+ KB. They begin to lose quality beyond that reduction.

https://github.com/haystack-hq/website/commit/2a3646c0193d754f72952501dee694be1bc87928
