### ISSUE TITLE
Early Access page Needs new Date Formatting

### ISSUE THREAD

**Issue by goldbatzmaru** [haystack-hq/website#9]
Mirror https://github.com/haystack-hq/website/commit/4d5307d26c231daa6bbdb4cb8453d6e77cdbddc6 on the Early Access page

**Comment by jajajaime** [comment]
Maybe that section can be separated to its own component, so both pages include it.

**Comment by goldbatzmaru** [comment]
Good suggestion

**Comment by goldbatzmaru** [comment]
I have turned the Contact Info card into it's own component to be used on both form pages.

https://github.com/haystack-hq/website/commit/2a635f34f9e9ba8f13c36d4c4e6e664673e3987e
